server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/backend
    username: postgres
    password: Postgres2024!
  jpa:
    hibernate:
      ddl-auto: create-drop
